### ISSUE TITLE
Security Profiles Firejail/AppArmour

### ISSUE THREAD

**Issue by gitbugged** [Bitmessage/PyBitmessage#1140]
I'm pretty much a noob at writing these, so I would wait for someone such as @chiraag-nataraj or other regular firejail users to critique these and see if it can be hardened more. Once they are finalized we can push for upstream inclusion.

However, they are working for me from git version of PyBitmessage located at $HOME.

Firejail:

    # Firejail profile for PyBitmessage
    # This file is overwritten after every install/update
    # Persistent local customizations
    include /etc/firejail/pybitmessage.local
    # Persistent global definitions
    include /etc/firejail/globals.local

    noblacklist ${HOME}/.config/PyBitmessage
    noblacklist ${HOME}/PyBitmessage/src/bitmessagemain.py

    include /etc/firejail/disable-common.inc
    include /etc/firejail/disable-devel.inc
    include /etc/firejail/disable-passwdmgr.inc
    include /etc/firejail/disable-programs.inc

    mkdir ~/.config/PyBitmessage
    whitelist ~/.config/PyBitmessage
    include /etc/firejail/whitelist-common.inc

    caps.drop all
    netfilter
    no3d
    nodvd
    nogroups
    nonewprivs
    noroot
    notv
    novideo
    protocol unix,inet,inet6
    seccomp
    shell none

    disable-mnt
    private-dev
    private-bin pybitmessage,python,python2,python2.7
    private-tmp

    noexec ${HOME}
    noexec /tmp

AppArmour:

    #include <tunables/global>

    /home/*/PyBitmessage/src/pybitmessagemain.py {

        #include <abstractions/base>
        #include <abstractions/python>

        owner @{HOME}/PyBitmessage/ r,
        owner @{HOME}/PyBitmessage/** mr,
        owner @{HOME}/PyBitMessage/nw ix,
        owner @{HOME}/PyBitmessage/config/** mrwk,

        owner @{HOME}/.config/PyBitmessage/ rw,
        owner @{HOME}/.config/PyBitmessage/** rwmk,

        / r,

        network,

    }

**Comment by PeterSurda** [comment]
Thanks

**Comment by chiraag-nataraj** [comment]
Hey @gitbugged! I'm flattered 😊. The only thing I would change is `whitelist ${DOWNLOADS}` as well so that you can share files with the program easily. I've never used PyBitmessage, but I'd also think you need to `whitelist ${HOME}/PyBitmessage/` (unless that was just for testing?). You could also use `private-etc` to lock down which system files the program can see (for network-facing programs, you usually need a combination of `/etc/hosts`, `/etc/resolv.conf`, and possibly other files depending on the program, including `/etc/localtime` and `/etc/nsswitch.conf` - you'll have to play around until you hit the right combination of files). There are other directives as well (like `private-lib`), but I haven't yet figured out how those work enough to get them to work reliably. Another directive that might be useful is `seccomp.block-secondary`. But yeah, overall looks good! 👍

**Comment by gitbugged** [comment]
Cool! Some distros are also providing their own install path which would break the profiles, not sure how to go about fixing that. Also, the "private-bin" may also need to change depending on python version installed, or removed even though it is good for security, since it fails to start on trivial python changes.

**Comment by PeterSurda** [comment]
In the meantime I familiarised myself a bit with firejail and now use it for firefox and mutt. Since PyBitmessage now supports setuptools, the firejail module included will use the global and user library paths (normally /usr/local/lib/python2.7/site-packages and ~/.local/lib/python2.7/site-packages). Distros which package it can include their own patch to update based on their own policy, such as /usr/lib/python2.7/site-packages).

Running directly from source without running setuptools probably isn't the best option when using firejail as it has to compile the modules during runtime which requires write access to source and I'd block that through firejail or at least apparmor.

**Comment by dmp1ce** [comment]
I tried the firejail profile on Arch Linux but bitmessage didn't start.

```
> firejail pybitmessage
Reading profile /etc/firejail/pybitmessage.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Parent pid 31239, child pid 31240
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
TESTING warning: noblacklist /home/xxxx/.config/PyBitmessage not matched by a proper blacklist command in disable*.inc
TESTING warning: noblacklist /home/xxxx/PyBitmessage/src/bitmessagemain.py not matched by a proper blacklist command in disable*.inc
Child process initialized in 34.55 ms

Parent is shutting down, bye...
```

**Comment by PeterSurda** [comment]
You probably have to replace the `noblacklist`with `whitelist` and add `private-home` but I haven't tested anything yet. You're better off using setuptools first so that you'll get compiled python code, and then whitelist the directory where it was installed.

**Comment by dmp1ce** [comment]
Where are the steps for compiling bitmessage? Should I follow the instructions [here](https://bitmessage.org/wiki/Compiling_instructions)?

**Comment by PeterSurda** [comment]
Yes.

**Comment by dmp1ce** [comment]
I believe I'm running a compiled bitmessage but I am still getting a crash when using Firejail.

```
> firejail pybitmessage
Reading profile /etc/firejail/pybitmessage.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Parent pid 9453, child pid 9454
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
TESTING warning: noblacklist /home/dmp1ce/.config/PyBitmessage not matched by a proper blacklist command in disable*.inc
TESTING warning: noblacklist /home/dmp1ce/PyBitmessage/src/bitmessagemain.py not matched by a proper blacklist command in disable*.inc
Child process initialized in 32.22 ms
Traceback (most recent call last):
  File "/usr/local/bin/pybitmessage", line 11, in <module>
    execfile(script_file, new_globals)
  File "/usr/lib/python2.7/site-packages/pybitmessage/bitmessagemain.py", line 19, in <module>
    import depends
  File "/usr/lib/python2.7/site-packages/pybitmessage/depends.py", line 5, in <module>
    import pyelliptic.openssl
  File "/usr/lib/python2.7/site-packages/pybitmessage/pyelliptic/__init__.py", line 16, in <module>
    from .openssl import OpenSSL
  File "/usr/lib/python2.7/site-packages/pybitmessage/pyelliptic/openssl.py", line 549, in <module>
    loadOpenSSL()
  File "/usr/lib/python2.7/site-packages/pybitmessage/pyelliptic/openssl.py", line 538, in loadOpenSSL
    libdir.append(find_library('ssl'))
  File "/usr/lib/python2.7/ctypes/util.py", line 274, in find_library
    return _findSoname_ldconfig(name) or _get_soname(_findLib_gcc(name))
  File "/usr/lib/python2.7/ctypes/util.py", line 103, in _findLib_gcc
    stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Parent is shutting down, bye...
```

**Comment by PeterSurda** [comment]
It looks like you need to add `sh,ldconfig,gcc` to the `private-bin` option. Please not it's still under testing so be careful.

**Comment by dmp1ce** [comment]
Should I need gcc? Am I building bitmessage incorrectly? I'm working on improving the Arch Linux PKGBUILD so it runs with compiled binaries. Maybe I should create a new issue.

**Comment by PeterSurda** [comment]
I had the same error and debugging showed that ctypes uses a shell with ldconfig and gcc to locate libraries. Maybe you don't need to whitelist gcc and sh and ldconfig is enough.

**Comment by dmp1ce** [comment]
I added the firejail profile to the package I'm maintaining for Arch Linux. Users should be able to run `firejail pybitmessage`.

**Comment by sigoa** [comment]
for those who search all ISSUES for SECURITY related issues using the "security" label, here is a crosslink to the famous "eval() vuln" :  :1st_place_medal:   https://github.com/Bitmessage/PyBitmessage/commit/3a8016d31f517775d226aa8b902480f4a3a148a9    :camel: 

I posted it here , where it might be seen as off-topic, since it is the only ISSUE labeled "security" and will be found quickly thus.

**Comment by PeterSurda** [comment]
Firejail profile addressed in https://github.com/netblue30/firejail/pull/2092

**Comment by g1itch** [comment]
Merged upstream
