### ISSUE TITLE
Microsoft owns Github, any plans in moving to Gitlab?

### ISSUE THREAD

**Issue by colt0** [Bitmessage/PyBitmessage#1267]
For obvious security reasons and for the love of freedom, are you considering moving the code to a more secure platform?

**Comment by PeterSurda** [comment]
All code, releases and binaries are signed. At this moment I don't see the need to move.

**Comment by dakar3882** [comment]
With all do respect @PeterSurda you can sign those binaries and releases 1000 times it still wont mean that the code is secure, since from the moment you host your code under the influence and power of Microsoft you have no control over whats going behind the scenes whatsoever.
Lets assume for instance that Microsoft doesn't have bad intentions for the open source code community, i can tell you now that Microsoft is not the one pulling the strings here.
There's plenty of ways that all code on Github can be compromised and commits can be changed without the date actually being changed.  Covert Backdoors can be injected in the code and hidden in plain sight.  All this might sound over-exaggerated, but in the end the fact remains that its realistic and very possible.
All that being said, if Bitmessage remains on here..people should consider it insecure, or at least MORE insecure than what it was.  The point is to make it as secure as possible, but leaving it in the hands of Microsoft i doubt that very much.

I hope you can consider moving this to GitLab/Sourceforge.

**Comment by PeterSurda** [comment]
Signing all code and binaries makes manipulations visible.
