### ISSUE TITLE
MemoryError in network loop

### ISSUE THREAD

**Issue by AyrA** [Bitmessage/PyBitmessage#1305]
After running the latest bitmessage Version (0.6.3.2) for a while it will eventually throw the error below.

```
Exception in thread ReceiveQueue_0:
Traceback (most recent call last):
  File "C:\python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Projects\PyBitmessage\src\network\receivequeuethread.py", line 43, in run
    BMConnectionPool().getConnectionByAddr(dest).process()
  File "C:\Projects\PyBitmessage\src\network\advanceddispatcher.py", line 61, in process
    if not getattr(self, "state_" + str(self.state))():
  File "C:\Projects\PyBitmessage\src\network\bmproto.py", line 98, in state_bm_command
    retval = getattr(self, "bm_command_" + str(self.command).lower())()
  File "C:\Projects\PyBitmessage\src\network\bmproto.py", line 290, in bm_command_getdata
    self.append_write_buf(protocol.CreatePacket('object', Inventory()[i].payload))
  File "C:\Projects\PyBitmessage\src\network\advanceddispatcher.py", line 35, in append_write_buf
    self.write_buf.extend(data)
MemoryError

```

At that point most of the network system seems to stop working. Sending messages is still possible though as long as the client is connected to some nodes.

Not sure actually what `MemoryError` in this context means since the client runs on a machine with 12 GB of memory.

RAM usage in the client seems unreasonably high. My client is idling and uses 214 MB of memory which is more than enough to fit the message file multiple times.

**Comment by AyrA** [comment]
After 20 Minutes the client is now at over 500 MB of consumed memory

**Comment by PeterSurda** [comment]
So, two issues, MemoryError and memory consumption. The MemoryError I believe was fixed since the release. Memory consumption is slightly better too, but the most radical change was between 0.6.2 and 0.6.3 already, so it's actually much less than before. Mostly, the memory is consumed by network buffers, inventory buffer and stuff that's beyond my capability to trace. With 12GB or RAM you should be able to handle over a thousand connections, but asyncore will fully load a single core on your CPU before you reach that.

**Comment by PeterSurda** [comment]
This is probably fixed. There is still some performance issues with asyncore (mainly #1379 and to a lesser extent #1380), but there should be no more memory issues.
