### ISSUE TITLE
UI handling of deleting addresses

### ISSUE THREAD

**Issue by PeterSurda** [Bitmessage/PyBitmessage#1441]
Even though the QT UI doesn't allow deleting of addresses, the API does. And when you delete it through the API, the QT interface throws an exception as was reported in the BM chan.

This case should be handled, while at the same time I think that not giving an option to delete addresses from the UI is correct.

> Yes. Or at least I tried.
>
> ------------------------------------------------------
> Did you delete an address using the API?
> 
> Peter Surda
> Bitmessage core developer
> 
> > What would cause this error? How to determine cause precisely?
> > 
> > =========
> > API error
> > =========
> > 
> > 127.0.0.1 - - [02/Mar/2019 23:50:16] "POST / HTTP/1.1" 200 -
> > 2019-03-02 23:50:16,654 - CRITICAL - Unhandled exception
> > Traceback (most recent call last):
> >   File "bitmessage/src/bitmessageqt/__init__.py", line 4082, in
> > tableWidgetAddressBookItemChanged
> >     self.rerenderComboBoxSendFrom()
> >   File "bitmessage/src/bitmessageqt/__init__.py", line 2176, in
> > rerenderComboBoxSendFrom
> >     addressInKeysFile, 'enabled')  # I realize that this is poor
> > programming practice but I don't care. It's easier for others to
> > read.
> >   File "/usr/lib/python2.7/ConfigParser.py", line 368, in getboolean
> >     v = self.get(section, option)
> >   File "bitmessage/src/bmconfigparser.py", line 71, in get
> >     raise e
> > NoSectionError: No section: 'BM-2cT9KGmCbPEUqsJymSLRLWuGtvTLwHkVjA'

**Comment by navjotcis** [comment]
I have tried to reproduce the above issue so for that, we need to check it with API so
I have put but below-given lines in the keys.dat file

> apienabled = true
> apiport = 8442
> apiinterface = 127.0.0.1
> apiusername = username 
> apipassword = password

and then I have created api object of xmlrpclib.serverproxy
api = xmlrpclib.ServerProxy("http://username:password@127.0.0.1:8442/")

then I have created and address in the address book and keys.dat file
then after that, I have modified the api_client.py module for testing so
I have tried to delete address book address one by one 
using api.deleteAddressBookEntry('BM-2cVWHAFEaHjXYWgK8eJWmTKqWXkrRWePgC')
and it is working fine then after that I have tried to delete the keys.dat file address one by one
using below command
api.deleteAddress('BM-2cWYXBbraeFVMyVQLW8fAezXQGBFHbKFQ1')
and it is also working fine so this issue is fixed now because I have performed multiple 
tests on it and it is not crashing.

**Comment by PeterSurda** [comment]
looks fixed
