### ISSUE TITLE
Various API Errors in latest Release (0.6.3.2)

### ISSUE THREAD

**Issue by AyrA** [Bitmessage/PyBitmessage#1468]
The latest release has various API errors:

## sendBroadcast

API Error 0021: Unexpected API Failure - global name 'streamNumber' is not defined

since this is not an argument we can supply, I assume it's some internal error in the API handler.

## getStatus

API Error 0015: The length of ackData should be 32 bytes (encoded in hex thus 64 characters).

In response to an ackData returned by sendMessage. One of those two API functions is not behaving properly.

----

**Note: The latest release happened over a year ago, maybe it's time to create a new one.**

**Comment by PeterSurda** [comment]
Can you try with the latest development snapshot: https://download.bitmessage.org/snapshots/win32/ ? It may have been fixed in the meantime.

The issue with releases are proper Windows and OSX builds, which take a lot of time and need to be automated. Once the infrastructure is in place I'll make daily snapshots again, and once they have been tested I can release.

**Comment by g1itch** [comment]
OK, I added the check for `getStatus()` to my api refactoring branch: e9f4109.

**Comment by navjotcis** [comment]
I have gone through the above issue so here I have written a test case for sending Broadcast and checking the issue put test cases are successfully passing so I think this issue does not exist anymore.https://github.com/Bitmessage/PyBitmessage/pull/1676

**Comment by PeterSurda** [comment]
Maybe fixed in #1382
