### ISSUE TITLE
socket error on sendato

### ISSUE THREAD

**Issue by sashamd** [Bitmessage/PyBitmessage#1583]
When internet connection drops pybitmessage CPU utilization spikes to 100% and debug.log is quickly filled with 'ERROR - socket error on sendato: [Errno 101] Network is unreachable'.

OS: Ubuntu 16.04.6 LTS
Commit: a69732f060608428ddfebf608bdb3c8751e296ce

**Comment by navjotcis** [comment]
I have tried to check the issue so here when we disconnect the internet then socket connection gives exception so that already handled what's an issue with that? I don't understand the problem here

**Comment by sashamd** [comment]
Python2 doesn't work anymore on my system and PyBitmessage is shelved until better times. Sorry, I can't help with this right now.

**Comment by navjotcis** [comment]
I have tested it again and found some strange behavior because when the user disconnects to the internet the socket connection start giving error so in that case, it is closing socket connection I thought which is wrong because when I again connected with the internet then it is not connecting with the socket so I have commented close connection in udp.py module

- -            if e.errno == 101:
- -                self.announcing = False
- -                self.socket.close()
-              retval = 0
- +            retval = len(self.write_buf)
- +            # if e.errno == 101:
- +            #     self.announcing = False
- +            #     self.socket.close()

and then I have test the whole process again and now it is connecting through the socket after internet connection from a disconnected state

**Comment by PeterSurda** [comment]
Fixed in #1676
