### ISSUE TITLE
QT Interface problems on Ubuntu Xenial

### ISSUE THREAD

**Issue by PeterSurda** [Bitmessage/PyBitmessage#1744]
I have reports that there are problems with PyBitmessage on Xenial with the QT interface.

**Comment by kdcis** [comment]
Hi, I'll look at it.

**Comment by kdcis** [comment]
Hi,
The project is successfully running now in Ubuntu 16.04 after discussion & installing dependencies on VM. 
I've checked my personal systems project setup & found python-qt4 versioning issue, tried resolving it but still facing some issue in my personal system's pip. It may be because of the pip version dependency, as i have older pip version, but because of some other project setup I can't update my pip version in my system.

**Comment by PeterSurda** [comment]
Local issue.
