### ISSUE TITLE
Strange error: Thread crashes on startup

### ISSUE THREAD

**Issue by AyrA** [Bitmessage/PyBitmessage#530]
I just noticed this error showing up during startup.

Usually when working with threads please check periodically if they are still running and in case they are not, put the failed task to the end of the queue, so it does not blocks others. Then restart the thread.

For some reason POW is no longer done for any messages.

```
making request for v4 pubkey with tag: 50136c5a38f928e991b3061c3c3e3492d76cf7202f393133c44b356bd96a584d
Done in 1.15400004387: 1186106 with value 3562510383726 < 4102923503938
Found proof of work 3562510383726 Nonce: 1186106
Exception in thread Thread-2:
Traceback (most recent call last):
  File "Q:\Python27\lib\threading.py", line 808, in __bootstrap_inner
    self.run()
  File "Q:\PyBitmessage\src\class_singleWorker.py", line 60, in run
    self.sendMsg()
  File "C:\AdminRoot\TBM\PyBitmessage\src\class_singleWorker.py", line 503, in sendMsg
    self.requestPubKey(toaddress)
  File "Q:\PyBitmessage\src\class_singleWorker.py", line 897, in requestPubKey
    shared.inventorySets[streamNumber].add(inventoryHash)
KeyError: 1
```

**Comment by PeterSurda** [comment]
@AyrA does this still happen with the latest code?

**Comment by AyrA** [comment]
I don't know. I have stopped using the bitmessage client completely after I implemented the gateway.

You can test this, by saving an empty knownnodes.dat (just pickle.dump an empty list) and then reopening the client if I remember correctly.

It boild down to the fact, that if there is a network problem, bitmessage slowly deletes each entry, as it can no longer connect, eventually leaving the list empty.

**Comment by PeterSurda** [comment]
@AyrA Thanks, I think I understand your explanation.

**Comment by PeterSurda** [comment]
I'm not fully sure, but I think that this happens when you launch PyBitmessage and your worker thread starts creating proof of work for pending messages or pubkey requests before the outbound network connections initialise. This is in theory possible, because the main thread loads your encryption keys between launching the worker thread and calling connectToStream (where inventorySet is properly initialised). If that's the cause, a fix is super easy, just initialise the inventorySet earlier to a state that does not have a missing key for stream 1.

You are pretty much the only one that will realistically trigger this, because you have many addresses in keys.dat and a GPU PoW at the same time. So your worker thread is fast, and the time between launching it and initialising the inventorySet is long. I doubt that I will be able to reproduce this without recreating such an environment. So I made the probable fix without trying to reproduce it.

If anyone still has this problem, let me know, including how to reproduce it.

**Comment by AyrA** [comment]
I solved it myself by fiddling with the thread start order. Has worked for now but certainly is not professional. At the moment, there are close to 15000 active addresses in the system, so if you want to simulate it yourself, you could generate many dummy addresses in your client and try it I assume.
For obvious reasons I can't give you my address list.

**Comment by PeterSurda** [comment]
I don't want to allocate more time on this for the time being unless I know someone is affected.
