### ISSUE TITLE
Bitmessage does not shutdown correct in deamon mode

### ISSUE THREAD

**Issue by merlink01** [Bitmessage/PyBitmessage#549]
import os
    #Here is a Testscript:

    import time
    import tempfile
    import threading
    import bitmessagemain

    #Define Working Path
    path = tempfile.mkdtemp()
    os.environ["BITMESSAGE_HOME"] = path

    #Start and stop Bitmessage
    bm = bitmessagemain.Main()
    bm.start(daemon=True)
    time.sleep(30)
    bm.stop()

    #Check if all threads are closed
    while 1:
        time.sleep(2)
        thcount = 0
        threads = threading.enumerate()
        for th in threads:
            if th.is_alive():
                print th
                thcount += 1
        print thcount

**Comment by PeterSurda** [comment]
You are correct. This is what is leftover:

<singleListener(Thread-80, started daemon 5780)>
<addressGenerator(Thread-1, started daemon 1316)>
<_MainThread(MainThread, started 6532)>
<singleCleaner(Thread-5, started daemon 4344)>
<singleWorker(Thread-2, started daemon 12624)>

**Comment by PeterSurda** [comment]
I edited your post for aligning and formatting.

**Comment by PeterSurda** [comment]
Also, there are outgoingSynSender threads pending after sql shutdown, however these eventually timeout by themselves. The leftover 4 threads shutdown should be fixed (MainTread is the test program so we can ignore it).

**Comment by PeterSurda** [comment]
I made some minor mods so that it waits for outgoingSynSender at least.

**Comment by PeterSurda** [comment]
Most things are cleaned up now. The only thing that does not shut down correctly now are the outgoingSynSender threads. In order for them to shut down correctly, I need to modify the "connect" to be non-blocking. I tried that and it breaks SOCKS support (e.g. with Tor). So that requires more time. The program you wrote now simply has to wait up to 20 seconds for the connects to timeout and then the threads finish. PyBitmessage will not wait for these threads as then it appears as if it was frozen for 20 seconds and that looks bad.

This is not a priority issue anymore, I'm rescheduling the rest to later.

**Comment by PeterSurda** [comment]
singleWorker didn't shutdown correctly if you closed PyBitmessage quickly. This is now fixed. outgoingSynSender threads I'll leave as they are. I don't think it's important.
