### ISSUE TITLE
All log messages should be categorized and configurable

### ISSUE THREAD

**Issue by yurivict** [Bitmessage/PyBitmessage#656]
Currently, bitmessage by default prints a log of messages like this:
Could NOT connect to Peer(host='NNN.NNN.NNN.NNN', port=8444) during outgoing attempt. timed out

Every message should be categorized, timed, and every category should be made possible to disable in configuration screen. Also console/file/both should also be configurable.

**Comment by PeterSurda** [comment]
Fixed in mailchuck#cee1a59a8659da093bf281e365a3886a52003113.

On my LAN I setup logging to remote syslog and then I can look at the data through a web frontend and have a unified interface for all testing machines. It seems to be working well, the terminal screen is not cluttered either. It uses the standard logging.config.fileConfig interface so you can fine tune it. Just create a file "logging.dat" in the same directory as "keys.dat", and it will override the default logger settings. The commit log message contains an example config file (it's the same one I use, I just sanitised the syslog IP address).

**Comment by PeterSurda** [comment]
Also I added an additional logger to log unhandled exception.
