### ISSUE TITLE
Error running BitMessage on Ubuntu 14.04

### ISSUE THREAD

**Issue by springcoil** [Bitmessage/PyBitmessage#770]
Traceback (most recent call last):
  File "bitmessagemain.py", line 24, in <module>
    from api import MySimpleXMLRPCRequestHandler
  File "/home/peadar/PyBitmessage/src/api.py", line 18, in <module>
    import shared
  File "/home/peadar/PyBitmessage/src/shared.py", line 867, in <module>
    from debug import logger
  File "/home/peadar/PyBitmessage/src/debug.py", line 74, in <module>
    configureLogging()
  File "/home/peadar/PyBitmessage/src/debug.py", line 30, in configureLogging
    logging.config.dictConfig({
AttributeError: 'module' object has no attribute 'dictConfig'

I've tried running it a few different ways even setting up PyQt in a virtualenvironment to no avail.
I know this is a python error though it should be Python2.7 but when I check I seem to have the latest version of python.

**Comment by Atheros1** [comment]
By "the latest version of python" do you mean Python 3.x ?

**Comment by springcoil** [comment]
No I seem to be running python 2.6 rather than python 2.7. I have python
3.3 also installed on my computer

On Wed, Jan 21, 2015 at 5:22 PM, Jonathan Warren <notifications@github.com>
wrote:

> By "the latest version of python" do you mean Python 3.x ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Bitmessage/PyBitmessage/issues/770#issuecomment-70867836>
> .
>



-- 
Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by digital-dreamer** [comment]
Answers to [this question](http://askubuntu.com/questions/14615/how-do-i-make-the-terminal-run-python-3-1) on askubuntu.com explain how to change it.

**Comment by Atheros1** [comment]
Do try to run it using Python 2.7.

**Comment by ianozsvald** [comment]
I just had the same error as @springcoil (hey there!) after a fresh pull today. For some reason my api.py was 0 bytes, as were a set of other files. I deleted the src folder and did a `git checkout src` again, then all was fine.

**Comment by PeterSurda** [comment]
@springcoil I have ubuntu 14.04 and it works fine. I guess it had to do with python. The documentation at https://docs.python.org/2/library/logging.config.html says that logging.config.dictConfig is new in python 2.7. It looks like there's something wrong with your ubuntu because 14.04 comes with 2.7 and not 2.6

I don't think PyBitmessage is compatible with python 3.

@ianozsvald this is probably not the same issue, as the log says "api.py line 18", which means it's not empty. If I was you, I would do a filesystem check and smart check of the drive too.
