### ISSUE TITLE
keys.dat file should be encypted [feature request]

### ISSUE THREAD

**Issue by lunokhod** [Bitmessage/PyBitmessage#794]
As the title says, the user should be given the option to encrypt the keys.dat file with a passphrase. As it is now, the private keys are plaintext in an ascii file, which is not very secure....

**Comment by vxbinaca** [comment]
dm-crypt the hard disk?

**Comment by rand-func** [comment]
@vxbinaca  Dm-crypt is disk encryption tool, and disk encryption is based "all-or-nothing" security. If machine compromised when user logged-in and idle, disk encryption won't help. GPG, for example, asks for passphrase by default and encrypts private keys with it. In PyBitmessage, it will be somewhat hard to implement, because user will be required to input passphrase each time keys.dat is accessed.

**Comment by xiaokangwang** [comment]
Whenever client received a message (for you or not) you will need to input the password.(Or password will always in memory.)

**Comment by Adeor** [comment]
I think keeping the key in memory is a good compromise between comfort and security. Entering the key every time __any message__ is received is to extreme in my opinion.

**Comment by lunokhod** [comment]
Entering the key just once when launching the program would be better than having no key at all...

**Comment by vxbinaca** [comment]
Perhaps integration with common keychain managers (ex: Seahorse)? I would support this but (sadly) a lot of users are on Windows which doesn't have one out of the box. MacOS and Windows do.

However all three have disk encryption, two of which are able to convert the filesystem in situ to an encrypted one. So it appears thats the route to go to mitigate the problem of access to the database. You're talking about a complex engineering problem. Are you relying on an outside module to do the en/decryption? Had this module been vetted?

At least one of those disk encryption suites have been audited (BitLocker).

**Comment by Adeor** [comment]
what about using openssl for encryption? it is well audited and supported by windows, mac and linux.

**Comment by vxbinaca** [comment]
```what about using openssl for encryption?```

One fault with OpenSSL (and there have been a lot lately in case you haven't noticed) and the key database is at risk. The same could go for dm-crypt as well but thats a lot higher quality piece of software.

```audited```

By who? For what? FIPS compliance? OpenSSL is about the nastiest piece of code out there. Written in 5 different languages, including Assembly, it's the coding equivalent of "Extreme Hoarders". They have a DNS client in there (that is broken) that handles DNS in case your crappy network stack can't do it (any modern OS no matter how small can). Theres a sockets handler in there for network stacks without sockets. Compiling compatibility for VMS (MS-DOS), Windows 9x and MacOS classic. I could go on and on and on.

^^^You see those examples? Thats what happens when a simple piece of code takes on things it shouldn't be taking on. Encrypting the database is one of them - and I really don't like saying that but in this case it's true. I'm not seeing a lot of good alternatives for handling the encryption. Maybe GPG? But then all the writes it nags you for the key. Hand off the key to 

Look, you could rely on faulty and poorly written crypto to secure one spot of your disk (while the rest is open to attack to get your key database) or just encrypt your all hard disk and be done with it. If you can't encrypt the piece of hardware you're running, then maybe you shouldn't be running PyBitmessage on that hardware without disk crypto.

**Comment by Adeor** [comment]
` FIPS compliance?`
As far as I know openssl is [FIPS-certified](https://www.openssl.org/docs/fips/fipsnotes.html).

`OpenSSL is about the nastiest piece of code out there. [.....] I'm not seeing a lot of good alternatives for handling the encryption.`
yes, it really looks like openssl tried to solve to many problems. But I can't see any good alternatives, too. Are there some audited symmetric-only libs with python-bindings out there, that I didn't noticed?

The most famous python-interfaces are [pycrypto](https://pypi.python.org/pypi/pycrypto) and [cryptography](https://pypi.python.org/pypi/cryptography/0.9.3). I didn't read their full documentation, but it sounds like they are at least *kinda secure*.

`If you can't encrypt the piece of hardware you're running, then maybe you shouldn't be running PyBitmessage on that hardware without disk crypto.`
I think that the issue is more about having an additional layer of security while the computer is running. In that case disk encryption is useless and encrypting just the keys.dat *could be useful* in some cases. Also on a multi-user-system it *could prevent* other users from stealing the key as long as the admin is trustworthy.

 `faulty and poorly written crypto` is not really a long-term solution, but using the least worse solution is (in my opinion) better then no encryption at all as long as the performance impact is negligible.

**Comment by vxbinaca** [comment]
So is PyBitmessage a security app or it a messaging app? I think if they take on this matter and it becomes too much of a time sink then the actual anonymity and security of the messaging portion will suffer.

Just encrypt your entire hard drive. It prevents a lot of the attacks that would give rise to access to the system to steal the key (that sits in memory anyway, and y'all are disabling DMA ports on your machines, right?). OTF encryption is going to store the key in memory anyway so you don't have to type a password for every read/write operation on the DB, so why not just take care of the whole OS?

'In that case disk encryption is useless'

Right with a memory attack like Cold Boot or Rowhammer, right? Well when you dump the ram, you're getting that DB key too, in fact you're getting the DB too since chances are it's in memory. Again, we com back to: Why over-engineer the OS when encrypting the hard disk prevents attacks that aren't Cold Boot, which for now is most of the attacks on portable machines.

**Comment by lunokhod** [comment]
When I first posed this question, I thought that i would be possible to do something similar to bitcoin:

- optionally encrypt the keys.dat file when the user first runs bitmessage
- check for new messages using the public key of the receiver
- require a passphrase to unlock the keys.dat file to read the message
- have a command similar to: walletpassphase pass time. The time would be set in the bitmessage preferences, and could be "indefinite" if you don't care.

The reason I brought this up is: It would be very easy for someone to copy your keys.dat file to a usb thumb drive during the time that it takes you to go to the bathroom. It is for this reason that I encrypt my bitcoin wallet even though it is on an encrypted drive.

**Comment by ishbir** [comment]
Note that it isn't possible to "check for new messages using the public key of the receiver" as Bitmessage tries to decrypt each message with all the private keys that it has. There's no 'marker' that says that could reveal that this message belongs to you. Therefore, it's impossible to not keep unencrypted private keys in memory.

As for encrypting the keyfile and the messages store, we at Monetas are creating an alternative client for Bitmessage which has all these features built in. It's being designed to work with standard e-mail software. It's not done yet but we hope to get it alpha-ready in a week or so. Check out: https://github.com/monetas/bmd and https://github.com/monetas/bmclient

**Comment by Atheros1** [comment]
This discussion is valuable and I understand the concerns being raised. This would be quite a big task to implement; encrypting the keys wouldn't be terribly difficult but if we do that then we should also encrypt the messages on disk. I don't think that the feature would be particularly valuable against an attacker who can run programs on the computer as keyloggers are old, simple, and would be very effective at getting access not only to Bitmessage passphrases but also other online services. Full disk encryption would be a more-complete way of mitigating the physical-access problem.

So, for me personally, the work and and longer term code maintenance cost is not overcome by the benefit of added security. I'm not saying that it may not be done and won't be merged, only that I am not going to do it. I'm sorry. In the interest of keeping the list of issues clean, I wish to close the issue.
