### ISSUE TITLE
PyBitmessage does not check for duplicate invs in a GetData request.

### ISSUE THREAD

**Issue by DanielKrawisz** [Bitmessage/PyBitmessage#800]
I noticed that if you send a GetData message with duplicate invs, PyBitmessage will return the same object as many times as there are duplicates in the request.

**Comment by Atheros1** [comment]
Indeed. There are surely a large variety of ways to cause another client to waste bandwidth. If we ever encounter an alt-client which is badly programmed which is making these sorts of requests then we can add code to PyBitmessage to deal with it. But so far we haven't made an effort to identify and eliminate all of the possible ways to prevent an attacker from purposely wasting bandwidth because attempting to block such attacks would require a reasonable amount of overhead and might not even be successful. 

Thank you for reporting the issue.
