### ISSUE TITLE
Bitmessage + PGP

### ISSUE THREAD

**Issue by espress0** [Bitmessage/PyBitmessage#851]
Put gpg.exe to the same folder, and bitmessage will use it to encrypt or decrypt message.

**Comment by Atheros1** [comment]
This is not true.

**Comment by mirrorwish** [comment]
I think it was meant as a suggestion - not as a statement.

I don't like the idea, as encrypting messages with GPG doesn't really add any security, and has some serious privacy problems. But it might be worth discussing.

**Comment by krikmo** [comment]
> serious privacy problems.

@mirrorwish Do you mean that nodes distributing messages would know that message **X** and message **Y** came from the same user (same encryption key) or something else?

**Comment by mirrorwish** [comment]
No, not as long as messages are also encrypted with Bitmessage's encryption after PGP. I assume this was the intention. If they are not, you can use the `--hidden-recipient` flag, but I'm not sure if that is sufficient.

What I meant was that if you use the same PGP key for multiple Bitmessage identities, the recipients will know that these messages came from the same person. And even if you do not, the recipients will still know what algorithms you accept and what key length and type you use, which could be used to link different identities. And if you send your key to a key server, this server will know your IP address (unless you use Tor).

**Comment by krikmo** [comment]
Oh, I see.

**Comment by krikmo** [comment]
> --hidden-recipient

Is this what the [white paper](https://bitmessage.org/bitmessage.pdf) calls *Passive operative mode"? In which a node uses another to send acknowledgments? I thought it was yet to be created. Any obvious negative effects of using it?

**Comment by mirrorwish** [comment]
I was referring to the [`--hidden recipient` command line option in GnuPG](https://www.gnupg.org/documentation/manuals/gnupg/GPG-Key-related-Options.html).

"Passive operating mode" is not implemented, and I don't think it will be. It requires to do a harder proof of work, and at least one of the examples in the white paper is not secure (sending a pubkey request). But maybe it can be secure if implemented correctly.

**Comment by krikmo** [comment]
Thank you for all the insight. :)

**Comment by PeterSurda** [comment]
Passive mode (as described in the whitepaper) has actually two parts:
- not sending ACKs
- onion routing. The paper describes this for the use of ACKs, but it can also be used for normal messages.

The first part is implemented in 0.5.8, but undocumented, has no GUI and it has a minor bug (if the recipient changes the setting, people who already have his pubkey will not know that this has changed and will mistakenly wait for the ACK). The does_ack bitfield was already defined in the protocol but only fully implemented recently.

The second part isn't implemented in PyBitmessage, but I think it is a great idea. I have been thinking about how this can be done and I have some ideas:
- allocating an unused bitfield in the pubkey object to advertise that the address can act as an onion router. People can manually turn this on, or maybe PyBitmessage can detect if it is running all the time rather than only occasionally and can create a new routing address with this flag for this purpose.
- having a new message encoding or object type so that the router knows that he should just return the ACK without showing the message in the inbox. A new object type would also allow to have nodes that can determine whether to relay onion messages or not (so that not everyone has to distribute all the layers of each message)
- encrypting each layer with multiple public keys so that you have redundant routing

But this has nothing to do with PGP.
