### ISSUE TITLE
INSTALL.md is incomplete

### ISSUE THREAD

**Issue by yurivict** [Bitmessage/PyBitmessage#853]
1. List of dependencies is incomplete. For example, py-pbkdf2, py-ecc, py-pyelliptic are missing (among others).
2. You can add FreeBSD OS section, saying "Installs through 'bitmessage' package or 'net-p2p/bitmessage' port".

Trying to update the FreeBSD port, I can't even figure out where 'Cypher' package comes from, is it https://pypi.python.org/pypi/cypher?  Same with hmac_sha256.

**Comment by PeterSurda** [comment]
This is odd, because on other OSes, these packages are not necessary. Pyelliptic is included in PyBitmesage. I'll look at it.

**Comment by yurivict** [comment]
So you should list all required external dependencies.

And if some of the dependencies are bundled, it is probably a good idea to change the name of the bundled version so there is no confusion.

**Comment by PeterSurda** [comment]
I setup FreeBSD in a VM and am going through the build/test process. It looks like FreeBSD has the standard python installation split across several packages. It doesn't work like this on other OSes or linux distros. I'll write down the procedure and update the install instructions.

**Comment by yurivict** [comment]
The procedure is one of two lines:
```
(cd /usr/ports/net-p2p/bitmessage && make install clean)
or
pkg install bitmessage
```
The first line is to install from the port, the second one is to install from the package. By definition, on FreeBSD instructions can't be any more complex. FreeBSD port has been available for a few years.

**Comment by PeterSurda** [comment]
I tried running it from git and other than a minor ifdef change in bitmsghash.cpp to build the PoW module it works fine. py-pbkdf2, py-ecc or py-pyelliptic are not necessary, nor Crypt or anything else. The only modules it requires that are not a part of the official python distribution are pyqt, and that only if you want the gui. If you don't need the gui and run it as a daemon, a standard python is enough (2.7.6 or later, but 2.7.9 is preferred). FreeBSD seems to have split the official python into several packages and the only one I had to install was py27-sqlite3 (again, on other OSes this is not necessary because standard python build includes sqlite3). I'm not familiar with how ports work but if you need more info, let me know what.

**Comment by yurivict** [comment]
> I tried running it from git and other than a minor ifdef change in bitmsghash.cpp to build the PoW module it works fine.

Are you sure it actually worked with bitmsghash.so? It doesn't send a message when I try to send with bitmsghash.so on FreeBSD. "Waiting for their public key" Arch, I think, doesn't use bitmsghash.so.

**Comment by PeterSurda** [comment]
You're right, it probably does not calculate correctly and needs more than one ifdefs. I'll look at it and commit the patches. Other than that PyBitmessgage 0.6 works fine on FreeBSD.

**Comment by yurivict** [comment]
Yes, I tested it and it works. I will submit the port update.

**Comment by PeterSurda** [comment]
Thanks, I'll let you know once I sorted out the PoW module. Can you send me your email or bitmesage address? Use the contact support form.

**Comment by PeterSurda** [comment]
If you still want to have pybitmessage in the ports, please check the latest code for setup.py which includes detection for FreeBSD and has successfully been tested. It includes information about what packages to install as well.
