### ISSUE TITLE
BM still listens for inbound connections when connected through tor, green "light" is on.

### ISSUE THREAD

**Issue by yurivict** [Bitmessage/PyBitmessage#862]
Instance is configured to connect through SOCKS5/tor. "Listen for connections on port" is grayed out. Incoming connections should be disabled (because there is no HS support yet). Yet it shows the green light that means that there are incoming connections. netstat shows that it listens on the port that is grayed out by SOCKS5 option.

This is wrong because SOCKS5 forwards connections out to some other host with different IP, yet listening and incoming connections indicate that the real IP is exposed.

This is a security problem.

**Comment by PeterSurda** [comment]
There is a setting in the keys.dat, sockslisten, which controls whether it listens for incoming connections when proxy is SOCKS4 or SOCKS5. In the GUI, this is represented by the "Listen for incoming connections when using proxy" checkbox.

This will be slightly reworked when HS support is implemented to allow more flexibility.

**Comment by PeterSurda** [comment]
Recently I implemented hidden service support. Here is the documentation: https://bitmessage.org/wiki/FAQ#How_do_I_setup_Bitmessage_as_a_hidden_service_on_Tor
Depending on configuration, you can listen on clearnet, on hidden service or on both at the same time. There is no GUI for this yet but you can manually edit keys.dat.

**Comment by dogtopus** [comment]
Bitmessage still listens on the port globally even if `onionbindip` was set to 127.0.0.1 and `sockslisten` was false. Also it seems that Bitmessage doesn't use `onionport` at all but still follows the normal `port` setting.

**Comment by yurivict** [comment]
This is a security problem, because once the user asks for tor connection (onion* anything) he has the expectation of BM using tor instead of the clearnet. And the open port is an indication of the clearnet use.

I also don't like terms like "onionbindip" because they aren't self-explanatory. It looks like this is an expert term, and the user is expected to possess some expect knowledge, when in fact the decision is only "use tor" vs. "use clearnet".

**Comment by PeterSurda** [comment]
@dogtopus  You also need to specify `onionhostname` and it needs to include `.onion`, that's probably what's missing. Also, `onionport` is the external tor port, not the internal listening port. When you for example have

    HiddenServicePort 12345 127.0.0.1:8444

in your torrc, then 12345 is the `onionport` and 8444 is `port` in keys.dat.

**Comment by PeterSurda** [comment]
@yurivict PyBitmessage needs to know the tor hidden service configuration, because otherwise it doesn't know what port and hostname to advertise and noone will be able to connect to it. It is an expert setting, at least for the time being. For outgoing settings over tor, this is not necessary.

But there maybe something else wrong, I'll do some tests.

**Comment by yurivict** [comment]
Tor has the control port. BM can add onions through that control port.
But, to access the control port you need the right permission, and it also should be configured to be "on". So this can be done automatically, but requires some configuration change.

**Comment by PeterSurda** [comment]
> Tor has the control port. BM can add onions through that control port.
... and there is no standardised way to obtain this port, so you need to configure it anyway.

Besides, I don't believe that you should setup PyBitmessage as an onion service unless you know what you're doing. It does not improve your speed or anonymity, rather it helps other tor users. And if it's not working correctly, you'll just end up slowing others because they'll waste time timeouting.

**Comment by yurivict** [comment]
torrc should have `ControlPort 9051` line to enable it.
And the there is the "stem" python library that allows you to access it: https://stem.torproject.org/faq.html

So there is an easy way to access it.

As for the timeouts, this is a bug in BM. When the BM instance starts, it should register either as a clearnet host (ip:port), as an onion host (xxxxxx.onion), or as both. Onion peers can access both clearnet and other onion peers, clearnet peers can access only other clearnet peers.

It is done this way in ZeroNet actually - and works quite well.

**Comment by PeterSurda** [comment]
> torrc should have ControlPort 9051 line to enable it.

That makes too many assumptions. I don't have it turned on anywhere, and I also have setups with tor and BM on different machines. I also don't want PyBitmessage to randomly connect to ports to probe whether this or that is turned on (I'm already unhappy about probing for namecoin). I also think that if you know how to edit the torrc to enable ControlPort, you should also be able to create a new onion address.

If you bundle tor with PyBitmessage, that's a different case, then you have more control over deployment, but I don't have immediate plans for that.

> As for the timeouts, this is a bug in BM.

Where exactly is the bug?

> When the BM instance starts, it should register either as a clearnet host (ip:port), as an onion host (xxxxxx.onion), or as both. Onion peers can access both clearnet and other onion peers, clearnet peers can access only other clearnet peers.

This is how it works now, except it doesn't know its external IP address (say if you're behind NAT), that is determined by the other party. But this doesn't work with onion addresses since there the IP address is always the internal IP of the tor instance, so you need to make sure your tor and PyBitmessage agree on the setup.

**Comment by yurivict** [comment]
> This is how it works now, except it doesn't know its external IP address ...

There is the standard STUN protocol to solve exactly this problem. It learns the NAT settings and the external IP.

IMO, bundling tor is a bad idea. They have all means for the third parties to access tor through the control port. It is just disabled by default. So the user should be instructed to:
1. Enable the control port in /etc/tor/torrc:
```
ControlPort 9051
HashedControlPassword 16:{HEX-PASSWORD}
```
2. Restart tor
3. Copy the {HEX-PASSWORD} into the BM settings.

This is the standard way how tor operates. You are basically saying that this is too hard. BM doesn't need to probe anything. If the user chooses to use Tor, it should instruct the user to do the steps above, then BM should connect to localhost:9051, and fail if that fails. No probing.

**Comment by PeterSurda** [comment]
> There is the standard STUN protocol to solve exactly this problem. 

I don't want PyBitmessage to make random connections, besides learning the IP is not the primary problem. You can already learn the IP from UPnP server, or from the `version` command you receive. The problem is to verify whether others can connect to you, and make the change backwards compatible, or at least doesn't break anything important. I've been trying to come up with a reasonable solution but haven't fully made up my mind.

Besides, this doesn't help with the tor onion address.

> IMO, bundling tor is a bad idea.

I tend to agree.

> They have all means for the third parties to access tor through the control port. It is just disabled by default. 

So how about I add it as an alternative to manually specifying the onion address, and adjust the UI accordingly?

**Comment by yurivict** [comment]
> Besides, this doesn't help with the tor onion address.
STUN is only meant to be used when clearnet connections are enabled. But how does BM find its IP when there is no UPnP? You have to connect somewhere to learn it.

> So how about I add it as an alternative to manually specifying the onion address, and adjust the UI accordingly?

Okay. Actually, generating onion address manually practically means that it will likely be the same for a long time. Generating it automatically through the control port guarantees that it will change with every restart which is marginally more secure.

**Comment by bmng-dev** [comment]
The port only stays open when you change the network settings while PyBitmessage is running. Upon restart PyBitmessage behaves correctly. PyBitmessage also doesn't close existing connections nor scrub possibly identifying data such as the connection nonce when changing the network settings while it is running.

The "leaking" of the IP address was the result of connecting to the network over clearnet before switching to Tor and then as above not restarting PyBitmessage. It has always been a warning from the Tor Project not to mix clearnet and Tor activity. Additionally users are given the option on the first run of PyBitmessage to configure the network settings before any network activity occurs - this is the ideal time to configure PyBitmessage to use Tor without any risks. It can be reactivated by adding `dontconnect = true` to keys.dat.

It was the combined act of connecting to clearnet first and then switching to Tor without restarting that resulted in incoming clearnet connections being accepted while Tor is used for outgoing connections. Not connecting to clearnet first or simply restarting after configuring a proxy would prevent this situation, although there is definately room for improvement regarding what happens when the user changes network settings while PyBitmessage is connected.

**Comment by PeterSurda** [comment]
@bmng-dev Well, that explains it. While it certainly can be improved, even the port is open, if you have `sockslisten` disabled, the incoming connection should stall (timeout), except for the first one that comes in after turning `sockslisten` off. The port isn't closed, but the `sockslisten` check is performed before calling `accept` on the socket.

The networking subsystem will be redesigned with something asynchronous so I wouldn't worry about it too much.

**Comment by g1itch** [comment]
This looks outdated.
