### ISSUE TITLE
French time format is wrong: 12-hours without AM/PM instead of 24-hours

### ISSUE THREAD

**Issue by LGD-Fr** [Bitmessage/PyBitmessage#867]
I have something like (with the af0dfdc version on fedora 23 and the french language) :
- *jeu., 03 juin 2016 __01:45__*, instead of 
- *jeu., 03 juin 2016 __13:45__*.

Apparently I have the 12-hours format without the AM/PM indication, so morning and afternoon cannot even be discriminated…

**Comment by PeterSurda** [comment]
Hello, you can configure the time format manually in the config file keys.dat, the variable name is "timeformat". Just watch out because you have to escape % with %, so it's slightly different than strftime. In your case, just replace

    %%I

with

    %%H

Unfortuantely, as far as I know, there is no way to configure it in the GUI.

**Comment by LGD-Fr** [comment]
Thanks @PeterSurda, it works.

**Comment by bmng-dev** [comment]
For the french locale (and others) %p in strftime is empty or a single space. The absence of AM/PM for some locales is correct as 24 hour time is usually the norm and sometimes there is no one-to-one equivalent for "am" or "pm".
The default setting for timeformat during creation of keys.dat should be changed to simply %c for the better supported locale-specific datetime representation. The current default setting is unusual in some locales.

**Comment by LGD-Fr** [comment]
Thanks @bmng-dev !

**Comment by PeterSurda** [comment]
I merged your patch, @LGD-Fr .
