### ISSUE TITLE
Running for first time fails with OperationalError: no such table: inventory

### ISSUE THREAD

**Issue by crypdick** [Bitmessage/PyBitmessage#941]
Here is the error:

```
richard@motherload:~/Apps$ python2 PyBitmessage/src/bitmessagemain.py
Loading existing config files from /home/richard/.config/PyBitmessage/
Failed to load debug config from /home/richard/.config/PyBitmessage/logging.dat, using default logging config
(<class 'ConfigParser.NoSectionError'>, No section: 'formatters', <traceback object at 0x7f85fead1d88>)
Exception in thread SQL:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/richard/Apps/PyBitmessage/src/class_sqlThread.py", line 224, in run
    self.cur.execute(item, parameters)
OperationalError: no such table: inventory
```

Here are the commands I used (taken from `.bash_history`):
```
git clone https://github.com/Bitmessage/PyBitmessage
python PyBitmessage/src/bitmessagemain.py
touch ~/.namecoin/namecoin.conf
python2 PyBitmessage/src/bitmessagemain.py
```

**Comment by PeterSurda** [comment]
I think that you interrupted it when you first ran the script as it was in the middle of creating the tables. This isn't handled correctly. In the meantime, delete `~/.config/PyBitmessage/messages.dat`, but be warned, if you have any received or sent messages, if you have any subscriptions, they will be deleted as well.

**Comment by PeterSurda** [comment]
These are really warnings rather than errors and it's been reworked in the v0.6 branch. It means that
- you don't have a custom logging configuration so it's using the default one
- you don't seem to have namecoin running so it's disabling namecoin functionality
- you don't have libmessaging so it's disabling the new mail notifications / system tray menu. This is the only really important thing, most linux distros have a package for this somewhere (libmessaging-menu or something like this)

**Comment by g1itch** [comment]
It seems there is nothing to do here.
